#!/usr/bin/env bash
# all.sh — writes all.md and llms-full.txt from the area indexes. Rules: govna/publishing-filter.md ## Check Command
#
# Targets Bash 3.2+ (macOS system Bash): no associative arrays, mapfile,
# ${var^^}, or &>>. Needs rg, awk, sed, and coreutils; uses fd when present.
#
# Usage:
#   ./all.sh          write all.md and llms-full.txt
#   ./all.sh --diff   render to a temporary directory and compare; exit 1 when
#                     the committed files differ, and write nothing in the repository
# CHECK_ROOT overrides the repository root, as in check.sh.
# Exit: 0 written or current, 1 stale, 2 usage error.
set -uo pipefail
export LC_ALL=C

ROOT="${CHECK_ROOT:-}"
[ -z "$ROOT" ] && ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
cd "$ROOT" || exit 2

SITE='https://que.one'
AREAS='life mind society tech'
TMP=$(mktemp -d "${TMPDIR:-/tmp}/all.XXXXXX")
trap 'rm -rf "$TMP"' EXIT
TAB=$(printf '\t')

entries() { # every entry path, sorted; the four area indexes are not entries
  local dirs='' a
  for a in $AREAS; do [ -d "$a" ] && dirs="$dirs $a"; done
  [ -n "$dirs" ] || return 0
  # shellcheck disable=SC2086
  { if command -v fd >/dev/null 2>&1; then fd -e md . $dirs; else find $dirs -name '*.md'; fi; } \
    | sed 's#^\./##' | rg -v -e '^(life|mind|society|tech)/index\.md$' | sort
}

area_label() { # path -> Life, Mind, Society, or Tech
  local a="${1%%/*}"
  printf '%s' "$a" | awk '{ print toupper(substr($0, 1, 1)) substr($0, 2) }'
}

index_line() { # path -> the entry's bullet in the index of its own directory, or empty
  local f="$1" d n idx esc
  d=$(dirname "$f"); n=$(basename "$f")
  if [ "$n" = index.md ]; then n="$(basename "$d")/index.md"; d=$(dirname "$d"); fi
  idx="$d/index.md"
  [ -f "$idx" ] || return 0
  esc=$(printf '%s' "$n" | sed 's/[.]/\\./g')
  rg -m1 -e "^[-*] \[[^]]+\]\($esc(#[^)]*)?\)" "$idx" | head -n 1
}

title_of() { # path line -> title from the index line, else the first heading, else the file name
  local f="$1" line="$2" t=''
  [ -n "$line" ] && t=$(printf '%s\n' "$line" | sed -E 's/^[-*] \[([^]]+)\].*/\1/')
  [ -n "$t" ] || t=$(rg -m1 -e '^#{1,3} ' "$f" | sed -E 's/^#{1,3} +//; s/[[:space:]]+$//')
  [ -n "$t" ] || t=$(basename "${f%.md}")
  printf '%s' "$t"
}

desc_of() { # line -> the description after the link, or empty
  [ -n "$1" ] || return 0
  printf '%s\n' "$1" | sed -E 's/^[-*] \[[^]]+\]\([^)]*\)[[:space:]]*:?[[:space:]]*//; s/[[:space:]]+$//'
}

url_of() { # path -> absolute URL; an index page maps to its directory
  case "$1" in
    */index.md) printf '%s/%s/' "$SITE" "$(dirname "$1")" ;;
    *) printf '%s/%s.html' "$SITE" "${1%.md}" ;;
  esac
}

kind_of() { # path -> type front matter, or note
  local k
  k=$(awk 'NR==1 && $0!="---"{exit} NR>1 && $0=="---"{exit} NR>1 && index($0,"type:")==1 {v=$0; sub(/^type:[[:space:]]*/,"",v); print v; exit}' "$1")
  printf '%s' "${k:-note}"
}

body_of() { # path -> content without front matter
  awk 'NR==1 && $0=="---"{fm=1; next} fm==1 && $0=="---"{fm=0; next} fm==1{next} {print}' "$1"
}

render() { # outdir -> outdir/all.md and outdir/llms-full.txt
  local out="$1" f line t d a u k
  : >"$out/lines"
  {
    printf -- '---\ntype: reference\n---\n## All entries\n'
    printf '<!-- generated by all.sh from the area indexes; edit those, then run ./all.sh -->\n\n'
    printf 'Every entry on one page, A to Z, with its area. Type in the search box at the top to narrow the list. It matches titles, descriptions, and the text of every entry, and the find command of your browser works too. To search from the address bar, add `que.one/all.html?q=%%s` to your browser as a search engine.\n\n'
    printf '{%% include all-filter.html %%}\n\n'
  } >"$out/all.md"
  printf 'Bits\n%s\nFull text of every entry, generated by all.sh from the site source.\n\n' "$SITE" >"$out/llms-full.txt"
  entries | while read -r f; do
    [ -f "$f" ] || continue
    line=$(index_line "$f"); t=$(title_of "$f" "$line"); d=$(desc_of "$line")
    a=$(area_label "$f"); u=$(url_of "$f"); k=$(kind_of "$f")
    if [ -n "$d" ]; then printf '%s\t%s\t- [%s](%s) (%s): %s\n' "$t" "$f" "$t" "$f" "$a" "$d"
    else printf '%s\t%s\t- [%s](%s) (%s)\n' "$t" "$f" "$t" "$f" "$a"; fi >>"$out/lines"
    { printf '==== %s (%s) %s\nKind: %s\n\n' "$t" "$a" "$u" "$k"; body_of "$f"; printf '\n'; } >>"$out/llms-full.txt"
  done
  sort -t "$TAB" -k1,1f -k2,2 "$out/lines" | cut -f3- >>"$out/all.md"
  rm -f "$out/lines"
}

usage() { sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'; }

main() {
  local mode=write a rc=0
  for a in "$@"; do
    case "$a" in
      --diff) mode=diff ;;
      -h | -\? | --help) usage; return 0 ;;
      *) printf 'unsupported option %s\n' "$a" >&2; usage >&2; return 2 ;;
    esac
  done
  render "$TMP"
  if [ "$mode" = diff ]; then
    for a in all.md llms-full.txt; do
      if [ ! -f "$a" ]; then printf '%s: missing, run ./all.sh\n' "$a"; rc=1
      elif ! cmp -s "$TMP/$a" "$a"; then printf '%s: stale, run ./all.sh\n' "$a"; diff -u "$a" "$TMP/$a" | sed -n '1,20p'; rc=1; fi
    done
    return $rc
  fi
  cp "$TMP/all.md" all.md && cp "$TMP/llms-full.txt" llms-full.txt || return 2
  printf 'wrote all.md (%s entries) and llms-full.txt\n' "$(rg -c -e '^- \[' all.md)"
}

main "$@"
